
version: 2
jobs:
  deploy_hummus_layer:
    docker:
      - image: amazon/aws-lambda-nodejs

    environment:
       BASH_ENV: ~/.bashrc

    steps:
      - checkout
      - run:
          name: install hummus
          command: |
            mkdir -p dist/nodejs
            cp package.json dist/nodejs/
            cd dist/nodejs
            yarn --production
      - run:
          name: zip layer
          command: |
            cd dist
            zip -r /tmp/hummus-lambda-layer.zip nodejs
      - deploy:
          command: |
            aws lambda publish-layer-version --region "us-west-2" --layer-name "hummus-lambda-layer" --description "NodeJS module of Hummus library" --license-info "MIT" --compatible-runtimes "nodejs16.x" --zip-file "fileb:////tmp/hummus-lambda-layer.zip"

workflows:
  version: 2
  deploy-a-ronie:
    jobs:
      - deploy_hummus_layer:
          context:
              - aws-circleuser

